### ISSUE TITLE
[FEATURE REQUEST] is posible to get position all time?

### ISSUE THREAD

**Issue by jmsandamil** [fliverdev/rider#14]
Can show marker in map in real time when user is moving?

not add a mark in map, when user open map shows all near users and mark is moving if users moves¡

thank you a lot¡¡¡

**Comment by urmilshroff** [comment]
> Can show marker in map in real time when user is moving?
> 
> not add a mark in map, when user open map shows all near users and mark is moving if users moves¡
> 
> thank you a lot¡¡¡

I'm not sure what you are trying to say, but as far as I can understand, this functionality already exists and was recently added in #12. The nearby markers are also shown when the app is launched, regardless of swipe.

**Comment by jmsandamil** [comment]
I think that you not understand me...

https://youtu.be/jey_92ZzdDI

This is about I talk

**Comment by urmilshroff** [comment]
> I think that you not understand me...
> 
> https://youtu.be/jey_92ZzdDI
> 
> This is about I talk

Okay, I understand. But making the marker move constantly is not what we want. We need the marker to remain fixed, and if user moves too far away it gets deleted. That is what our app idea is about.

**Comment by jmsandamil** [comment]
Ahhh ok, thanks!!!

Sorry, how I can do this with you app?
Get always marker in users?

**Comment by urmilshroff** [comment]
> Ahhh ok, thanks!!!
> 
> Sorry, how I can do this with you app?
> Get always marker in users?

Run the app on 3 devices near each other, then mark location in all of them. A hotspot will be created. If a device moves 100m outside its marked location, its marker will be deleted.

**Comment by jmsandamil** [comment]
I have done that, but if within those 100 meters, if the user moves, the mark is not updated with the user's position, even if the user is in the hospot and within 100 meters the marks do not move.
