### ISSUE TITLE
[BUG] Hide red error screen while fetching location

### ISSUE THREAD

**Issue by urmilshroff** [fliverdev/rider#4]
A nice splash screen/loading screen should be displayed when the app is launched and location is being fetched (instead of the ugly red debug sreen).

This screen should disappear once the location is fetched, so a fixed timeout duration must not be used.

**Comment by sidgan22** [comment]
I would like to work on this

**Comment by urmilshroff** [comment]
@sidgan22 please take a look at the [CONTRIBUTING.md](https://github.com/fliverdev/rider/blob/master/CONTRIBUTING.md) file and work on the feature accordingly. Make sure you switch to the `dev` branch first. Thanks

**Comment by sidgan22** [comment]
okay cool!
